/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Search$Params as Search$Params } from './fn/ticket-controller/search';
export { search as search } from './fn/ticket-controller/search';
export type { Create$Params as Create$Params } from './fn/ticket-controller/create';
export { create as create } from './fn/ticket-controller/create';
export type { Assign$Params as Assign$Params } from './fn/ticket-controller/assign';
export { assign as assign } from './fn/ticket-controller/assign';
export type { Unassign$Params as Unassign$Params } from './fn/ticket-controller/unassign';
export { unassign as unassign } from './fn/ticket-controller/unassign';
export type { GetById$Params as GetById$Params } from './fn/ticket-controller/get-by-id';
export { getById as getById } from './fn/ticket-controller/get-by-id';
export type { Delete$Params as Delete$Params } from './fn/ticket-controller/delete';
export { delete$ as delete$ } from './fn/ticket-controller/delete';
export type { Update$Params as Update$Params } from './fn/ticket-controller/update';
export { update as update } from './fn/ticket-controller/update';
export type { Mine$Params as Mine$Params } from './fn/ticket-controller/mine';
export { mine as mine } from './fn/ticket-controller/mine';
export type { List1$Params as List1$Params } from './fn/comment-controller/list-1';
export { list1 as list1 } from './fn/comment-controller/list-1';
export type { Add$Params as Add$Params } from './fn/comment-controller/add';
export { add as add } from './fn/comment-controller/add';
export type { Delete1$Params as Delete1$Params } from './fn/comment-controller/delete-1';
export { delete1 as delete1 } from './fn/comment-controller/delete-1';
export type { Update1$Params as Update1$Params } from './fn/comment-controller/update-1';
export { update1 as update1 } from './fn/comment-controller/update-1';
export type { Register$Params as Register$Params } from './fn/auth-controller/register';
export { register as register } from './fn/auth-controller/register';
export type { Login$Params as Login$Params } from './fn/auth-controller/login';
export { login as login } from './fn/auth-controller/login';
export type { List$Params as List$Params } from './fn/user-controller/list';
export { list as list } from './fn/user-controller/list';
export type { GenerateAiSummary$Params as GenerateAiSummary$Params } from './fn/ticket-controller/ai-summary';
export { generateAiSummary as generateAiSummary } from './fn/ticket-controller/ai-summary';
export type { SuggestReply$Params as SuggestReply$Params, SuggestReplyResponse as SuggestReplyResponse } from './fn/ticket-controller/suggest-reply';
export { suggestReply as suggestReply } from './fn/ticket-controller/suggest-reply';
