/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AssignRequest } from './models/assign-request';
export type { CommentResponse } from './models/comment-response';
export type { CreateRequest } from './models/create-request';
export type { ErrorResponse } from './models/error-response';
export type { LoginRequest } from './models/login-request';
export type { PageableObject } from './models/pageable-object';
export type { PageTicketSummary } from './models/page-ticket-summary';
export type { RegisterRequest } from './models/register-request';
export type { SortObject } from './models/sort-object';
export type { TicketResponse } from './models/ticket-response';
export type { TicketSummary } from './models/ticket-summary';
export type { TokenResponse } from './models/token-response';
export type { UpdateRequest } from './models/update-request';
export type { UserResponse } from './models/user-response';
export type { UserSummary } from './models/user-summary';
