/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CommentResponse } from '../../models/comment-response';
import { CreateRequest } from '../../models/create-request';

export interface Add$Params {
  ticketId: string;
      body: CreateRequest
}

export function add(http: HttpClient, rootUrl: string, params: Add$Params, context?: HttpContext): Observable<StrictHttpResponse<CommentResponse>> {
  const rb = new RequestBuilder(rootUrl, add.PATH, 'post');
  if (params) {
    rb.path('ticketId', params.ticketId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CommentResponse>;
    })
  );
}

add.PATH = '/v1/tickets/{ticketId}/comments';
