/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserSummary } from '../models/user-summary';
export interface CommentResponse {
  aiGenerated?: boolean;
  author?: UserSummary;
  content?: string;
  createdAt?: string;
  id?: string;
  ticketId?: string;
}
