/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserResponse {
  active?: boolean;
  email?: string;
  fullName?: string;
  id?: string;
  role?: 'ADMIN' | 'AGENT' | 'USER';
}
